export enum actionTypes{
    USER_LOGIN_START = 'USER_LOGIN_START',
    USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
    USER_LOGIN_ERROR = 'USER_LOGIN_ERROR',

    USER_SIGNUP_START = 'USER_SIGNUP_START',
    USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR',

    LOAD_PRODUCTS_START = 'LOAD_PRODUCTS_START',
    LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS',
    LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR',

    LOAD_PRODUCT_DETAIL_START = 'LOAD_PRODUCT_DETAIL_START',
    LOAD_PRODUCT_DETAIL_SUCCESS = 'LOAD_PRODUCT_DETAIL_SUCCESS',
    LOAD_PRODUCT_DETAIL_ERROR = 'LOAD_PRODUCT_DETAIL_ERROR',
}